//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("CodeSmith Tools, LLC")]
[assembly: System.Reflection.AssemblyProduct("CodeSmith Generator")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2002-2014 CodeSmith Tools, LLC.  All rights reserved.")]
[assembly: System.Reflection.AssemblyVersion("6.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("7.0.2.15174")]
[assembly: System.Reflection.AssemblyInformationalVersion("7.0.2.15174")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "CodeSmith Tools, LLC";
    
    internal const string AssemblyProduct = "CodeSmith Generator";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyCopyright = "Copyright (c) 2002-2014 CodeSmith Tools, LLC.  All rights reserved.";
    
    internal const string AssemblyVersion = "6.0.0.0";
    
    internal const string AssemblyFileVersion = "7.0.2.15174";
    
    internal const string AssemblyInformationalVersion = "7.0.2.15174";
    
    private ThisAssembly() {
    }
}
